<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVnw3lt3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVnw3lt3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVnw3lt3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVnw3lt3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVnw3lt3\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vnw3lt3',
    'container.build_id' => '90f4c035',
    'container.build_time' => 1714719017,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVnw3lt3');
