<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOWeW1j4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOWeW1j4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOWeW1j4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOWeW1j4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOWeW1j4\App_KernelDevDebugContainer([
    'container.build_hash' => 'OWeW1j4',
    'container.build_id' => 'bc3d2b86',
    'container.build_time' => 1714914311,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOWeW1j4');
